# 剧本作用: 用于在远程主机上安装MySQL8
# 安装命令: ansible-playbook -i hosts install_mysql8.yml
# 软件下载: https://mirrors.aliyun.com/mysql/MySQL-8.0/mysql-8.0.28-1.el7.x86_64.rpm-bundle.tar

- hosts: all
  vars:
    # 安装包名称
    tarball: mysql-8.0.28-1.el7.x86_64.rpm-bundle.tar
    # mysql版本
    version: 8.0.28-1
    # mysql 安装包位置
    localPath: ~/developer/software/mysql
    # 安装目录
    target: /opt/soft/
    # 架构
    arch: x86_64
    # 发行版本
    release: el7

  tasks:
    - name: create installation directory
      file:
        path: "{{ target }}"
        state: directory

    # 复制本地安装包到远程服务器
    - name: copy tarball remote hosts
      copy: src={{ localPath }}/{{ tarball }} dest={{ target }}

    # 解压安装包
    - name: Decompressing files
      shell: chdir={{ target }} tar xvf {{ tarball }}

    # 安装RPM包
    - name: Install
      shell: chdir={{ target }} /usr/bin/rpm -ivh {{ item }}  --force --nodeps
      with_items:
        - "mysql-community-client-plugins-{{ version }}.{{ release }}.{{ arch }}.rpm"
        - "mysql-community-devel-{{ version }}.{{ release }}.{{ arch }}.rpm"
        - "mysql-community-common-{{ version }}.{{ release }}.{{ arch }}.rpm"
        - "mysql-community-libs-{{ version }}.{{ release }}.{{ arch }}.rpm"
        - "mysql-community-libs-compat-{{ version }}.{{ release }}.{{ arch }}.rpm"
        - "mysql-community-client-{{ version }}.{{ release }}.{{ arch }}.rpm"
        - "mysql-community-server-{{ version }}.{{ release }}.{{ arch }}.rpm"

    # 启动服务并设置开机启动
    - name: start and enable mysqld.
      service:
        name: mysqld.service
        state: started
        enabled: True

    # 显示初始化密码
    - name: Display password
      shell: grep "password" /var/log/mysqld.log
      register: password

    - name: debug
      debug: var=password.stdout verbosity=0

    # 清理安装包
    - name: clean tarball
      file:
        path: "{{ target }}/{{ tarball }}"
        state: absent

    # 清理rpm包
    - name: clean rpm
      shell: chdir={{ target }} rm -rf  mysql-community-*.rpm

    # 开放端口
    - name: open port
      firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled
        immediate: yes

    # 后续步骤
    # 查看临时密码
    # grep "password" /var/log/mysqld.log

    # 登录临时root用户, 使用上面临时密码
    # mysql -u root -p
      
    # 修改root账号密码
    # ALTER USER 'root'@'localhost' IDENTIFIED BY 'QWqw12!@';
      
    # 切换数据库
    # use mysql;
      
    # 修改root账号方便其他Host访问
    # UPDATE mysql.user SET host = '%' WHERE user = 'root';
      
    # 赋予所有权限
    # GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
      
    # 刷新权限
    # FLUSH PRIVILEGES;
      
    # 退出
    # quit;
