# 剧本作用: 用于在远程主机上安装单节点redis
# 安装命令: ansible-playbook -i hosts install_redis_single.yml
# 软件下载: https://download.redis.io/releases/redis-6.2.6.tar.gz

- hosts: all
  vars:
    # 安装包名称
    tarball: redis-6.2.6.tar.gz
    # redis 安装包位置
    localPath: ~/developer/software/redis
    # 解压目录名称
    unzipDir: redis-6.2.6
    # 安装目录
    target: /opt/soft
    # redis 密码
    password: ctoQhiPf3AdeIs34

  tasks:
    - name: Install Package
      yum:
        name:
          - gcc

    - name: create installation directory
      file:
        path: "{{ target }}"
        state: directory

    - name: copy tarball remote hosts
      copy: src={{ localPath }}/{{ tarball }} dest={{ target }}

    - name: Decompressing files
      shell: chdir={{ target }} tar zxvf {{ tarball }} -C {{ target }}

    - name: Compile && Install
      shell: chdir={{ target }}/{{ unzipDir }} make && make install

    - name: Copy config file
      shell: chdir={{ target }}/{{ unzipDir }} cp redis.conf /etc/redis.conf

    - name: modify redis.conf
      replace:
        path: "/etc/redis.conf"
        regexp: "bind 127.0.0.1 -::1"
        replace: "bind 0.0.0.0"

    - name: modify redis.conf
      replace:
        path: "/etc/redis.conf"
        regexp: "daemonize no"
        replace: "daemonize yes"

    - name: modify redis.conf
      replace:
        path: "/etc/redis.conf"
        regexp: "# requirepass foobared"
        replace: "requirepass {{ password }}"

    - name: modify redis.conf
      replace:
        path: "/etc/redis.conf"
        regexp: "appendonly no"
        replace: "appendonly yes"

    # 创建数据目录
    - name: create data directory
      file:
        path: "/usr/local/redis/data"
        state: directory

    # 修改数据目录
    - name: modify redis.conf
      replace:
        path: "/etc/redis.conf"
        regexp: "dir ./"
        replace: "dir /usr/local/redis/data/"

    # 复制service文件
    - name: copy service file
      copy: src=redis.service dest=/etc/systemd/system

    # 重载systemd
    - name: reload systemd
      shell: systemctl daemon-reload

    # 启动redis并设置开机启动
    - name: start and enable redis.
      service:
        name: redis.service
        state: started
        enabled: True

    # 开放端口（必要时取消注释）
#    - name: open port
#      firewalld:
#        port: 6379/tcp
#        permanent: yes
#        state: enabled
#        immediate: yes

    # 删除安装包
    - name: clean tarball
      file:
        path: "{{ target }}/{{ tarball }}"
        state: absent

    # 删除解压目录
    - name: clean dir
      file:
        path: "{{ target }}/{{ unzipDir }}"
        state: absent