
- hosts: hadoop
  vars:
    # 本地JDK位置
    jdk: /root/jdk-8u202-linux-x64.tar.gz
    # 安装目录
    target: /opt/soft
    # 环境变量文件
    env: /etc/profile

  tasks:
  - name: create installation directory
    file:
      path: "{{ target }}"
      state: directory
  - name: copy jdk remote hosts
    copy: src={{ jdk }} dest={{ target }}
  - name: Decompressing files
    shell: chdir={{ target }} tar zxvf jdk-8u202-linux-x64.tar.gz
  - name: create links
    file: src={{ target }}/jdk1.8.0_202 dest=/usr/local/java state=link
  - name: java_profile config
    shell: /bin/echo {{ item }} >> /etc/profile
    with_items:
        - \# Java Env
        - export JAVA_HOME=/usr/local/java
        - export JRE_HOME=/usr/local/java/jre
        - export CLASSPATH=.:\$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:\$JRE_HOME/lib:\$CLASSPATH
        - export PATH=\$JAVA_HOME/bin:\$PATH
  - name: take effect
    shell: source /etc/profile

  - name: clean tarball
    file:
      path: "{{ target }}/jdk-8u202-linux-x64.tar.gz"
      state: absent
