# 剧本作用: 使用rpm方式安装jdk
# 安装命令: ansible-playbook -i hosts install_jdk_rpm.yml
# 软件下载: https://repo.huaweicloud.com/java/jdk/8u202-b08/jdk-8u202-linux-x64.rpm

- hosts: all
  vars:
    # 安装包名称 jdk-11.0.19_linux-x64_bin.rpm jdk-17.0.7_linux-x64_bin.rpm jdk-21_linux-x64_bin.rpm
    tarball: jdk-8u202-linux-x64.rpm
    # 本地安装包位置
    localPath: ~/developer/software/jdk
    # 安装目录
    target: /opt/soft

  tasks:
    # 创建安装目录
    - name: create installation directory
      file:
        path: "{{ target }}"
        state: directory

    # 上传rpm包到远程主机
    - name: upload rpm
      copy: src={{ localPath }}/{{ tarball }} dest={{ target }}

    # 安装rpm包
    - name: install rpm
      shell: chdir={{ target }} /usr/bin/rpm -ivh {{ item }}  --force --nodeps
      with_items:
        - "{{ tarball }}"

    # 清理安装包
    - name: clean tarball
      file:
        path: "{{ target }}/{{ tarball }}"
        state: absent