# 源码编译安装python
# ansible-playbook -i hosts install_python.yml
- hosts: all
  vars:
    # 安装包名称
    tarball: Python-3.9.5.tgz
    # 本地安装包位置
    localPath: ~/developer/software/python
    # 解压目录名称
    unzipDir: Python-3.9.5
    # 安装目录
    target: /opt/soft
  tasks:
    # 安装常用软件
    - name: Install Package
      yum:
        name:
          - zlib
          - zlib-devel
          - bzip2-devel
          - openssl-devel
          - ncurses-devel
          - sqlite-devel
          - readline-devel
          - tk-devel
          - gcc
          - libffi-devel
    - name: copy tarball remote hosts
      copy: src={{ localPath }}/{{ tarball }} dest={{ target }}

    - name: Decompressing files
      shell: chdir={{ target }} tar zxvf {{ tarball }} -C {{ target }}

    - name: compile
      shell: chdir={{ target }}/{{ unzipDir }} ./configure --prefix=/usr/local/python3

    - name: compile
      shell: chdir={{ target }}/{{ unzipDir }} make && make install

    - name: create python link
      file:
        path: /usr/bin/python3
        state: absent

    - name: create pip link
      file:
        path: /usr/bin/pip3
        state: absent

    - name: create link3
      file:
        src: /usr/local/python3/bin/python3
        dest: /usr/bin/python3
        state: link

    - name: create link4
      file:
        src: /usr/local/python3/bin/pip3
        dest: /usr/bin/pip3
        state: link

    - name: create pip dir
      file:
        path: ~/.pip
        state: directory

    - name: copy pip.conf
      copy:
        dest: ~/.pip/pip.conf
        src: './pip.conf'

    - name: clean tarball
      file:
        path: "{{ target }}/{{ tarball }}"
        state: absent

    - name: clean unzipDir
      file:
        path: "{{ target }}/{{ unzipDir }}"
        state: absent

    - name: gather Python Version info
      shell: python3 -V
      register: version

    - name: debug
      debug: var=version.stdout verbosity=0
