# 剧本作用: 用于在远程主机上安装jdk 预编译版本
# 安装命令: ansible-playbook -i hosts install_jdk_binary.yml

- hosts: all
  vars:
    # 安装包名称
    tarball: jdk-8u202-linux-x64.tar.gz
    # 本地安装包位置
    localPath: ~/developer/software/jdk
    # 解压目录名称
    unzipDir: jdk1.8.0_202
    # 安装目录
    target: /opt/soft
    # 环境变量文件
    env: /etc/profile

  tasks:
    # 创建安装目录
    - name: create installation directory
      file:
        path: "{{ target }}"
        state: directory

    # 上传jdk包到远程主机
    - name: copy jdk remote hosts
      copy: src={{ localPath }}/{{ tarball }} dest={{ target }}

    # 解压jdk包
    - name: Decompressing files
      shell: chdir={{ target }} tar zxvf {{ tarball }} -C {{ target }}

    # 创建软连接 ln -s /opt/soft/jdk1.8.0_202 /usr/local/java
    - name: create links
      file: src={{ target }}/{{ unzipDir }} dest=/usr/local/java state=link

    # 配置环境变量
    - name: java_profile config
      shell: /bin/echo {{ item }} >> /etc/profile
      with_items:
        - \# Java Environment Variables
        - export JAVA_HOME=/usr/local/java
        - export JRE_HOME=/usr/local/java/jre
        - export CLASSPATH=.:\$JAVA_HOME/lib/dt.jar:\$JAVA_HOME/lib/tools.jar:\$JRE_HOME/lib:\$CLASSPATH
        - export PATH=\$JAVA_HOME/bin:\$PATH

    # 生效环境变量
    - name: take effect
      shell: source /etc/profile

    # 清理安装包
    - name: clean tarball
      file:
        path: "{{ target }}/{{ tarball }}"
        state: absent
